-- MySQL Script generated by MySQL Workbench
-- Tue Oct 27 15:11:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema yii2saramago
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yii2saramago
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yii2saramago` DEFAULT CHARACTER SET utf8 ;
USE `yii2saramago` ;

-- -----------------------------------------------------
-- Table `yii2saramago`.`Colecao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Colecao` (
  `id` INT NOT NULL,
  `tituloColecao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Cdu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Cdu` (
  `id` INT NOT NULL,
  `codCdu` VARCHAR(45) NULL,
  `designacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Obra` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(100) NULL,
  `tituloAlternativo` VARCHAR(100) NULL,
  `resumo` VARCHAR(255) NULL,
  `editor` VARCHAR(45) NULL,
  `ano` VARCHAR(4) NULL,
  `descricao` VARCHAR(255) NULL,
  `idioma` VARCHAR(45) NULL,
  `local` VARCHAR(45) NULL,
  `edicao` VARCHAR(45) NULL,
  `assuntos` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  `Colecao_id` INT NOT NULL,
  `Cdu_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Obra_Colecao1_idx` (`Colecao_id` ASC) VISIBLE,
  INDEX `fk_Obra_Cdu1_idx` (`Cdu_id` ASC) VISIBLE,
  CONSTRAINT `fk_Obra_Colecao1`
    FOREIGN KEY (`Colecao_id`)
    REFERENCES `yii2saramago`.`Colecao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Obra_Cdu1`
    FOREIGN KEY (`Cdu_id`)
    REFERENCES `yii2saramago`.`Cdu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Monografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Monografia` (
  `id` INT NOT NULL,
  `volume` VARCHAR(45) NULL,
  `paginas` VARCHAR(45) NULL,
  `isbn` VARCHAR(45) NULL,
  `Obra_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Monografia_Obra1_idx` (`Obra_id` ASC) VISIBLE,
  CONSTRAINT `fk_Monografia_Obra1`
    FOREIGN KEY (`Obra_id`)
    REFERENCES `yii2saramago`.`Obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`PublicacaoPeriodica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`PublicacaoPeriodica` (
  `id` INT NOT NULL,
  `volume` VARCHAR(45) NULL,
  `serie` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `isnn` VARCHAR(45) NULL,
  `frequencia` VARCHAR(45) NULL,
  `Obra_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PublicacaoPeriodica_Obra1_idx` (`Obra_id` ASC) VISIBLE,
  CONSTRAINT `fk_PublicacaoPeriodica_Obra1`
    FOREIGN KEY (`Obra_id`)
    REFERENCES `yii2saramago`.`Obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`MaterialAV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`MaterialAV` (
  `id` INT NOT NULL,
  `duracao` VARCHAR(45) NULL,
  `ean` VARCHAR(45) NULL,
  `Obra_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MaterialAV_Obra1_idx` (`Obra_id` ASC) VISIBLE,
  CONSTRAINT `fk_MaterialAV_Obra1`
    FOREIGN KEY (`Obra_id`)
    REFERENCES `yii2saramago`.`Obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Fundo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Fundo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `consultaTReal` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`TipoExemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`TipoExemplar` (
  `id` INT NOT NULL,
  `designacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`EstatutoExemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`EstatutoExemplar` (
  `id` INT NOT NULL,
  `estatuto` VARCHAR(45) NULL,
  `prazo` VARCHAR(45) NULL,
  `requisitavel` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Biblioteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Biblioteca` (
  `id` INT NOT NULL,
  `codBiblioteca` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `horarioAtividade` VARCHAR(45) NULL,
  `morada` VARCHAR(45) NULL,
  `localidade` VARCHAR(45) NULL,
  `codPostal` VARCHAR(45) NULL,
  `levantamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codBiblioteca_UNIQUE` (`codBiblioteca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Exemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Exemplar` (
  `id` INT NOT NULL,
  `cota` VARCHAR(45) NULL,
  `codBarras` VARCHAR(45) NULL,
  `suplemento` VARCHAR(45) NULL,
  `Fundo_id` INT NOT NULL,
  `TipoExemplar_id` INT NOT NULL,
  `EstatutoExemplar_id` INT NOT NULL,
  `Obra_id` INT NOT NULL,
  `Biblioteca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Exemplar_Fundo1_idx` (`Fundo_id` ASC) VISIBLE,
  INDEX `fk_Exemplar_TipoExemplar1_idx` (`TipoExemplar_id` ASC) VISIBLE,
  INDEX `fk_Exemplar_EstatutoExemplar1_idx` (`EstatutoExemplar_id` ASC) VISIBLE,
  INDEX `fk_Exemplar_Obra1_idx` (`Obra_id` ASC) VISIBLE,
  INDEX `fk_Exemplar_Biblioteca1_idx` (`Biblioteca_id` ASC) VISIBLE,
  CONSTRAINT `fk_Exemplar_Fundo1`
    FOREIGN KEY (`Fundo_id`)
    REFERENCES `yii2saramago`.`Fundo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exemplar_TipoExemplar1`
    FOREIGN KEY (`TipoExemplar_id`)
    REFERENCES `yii2saramago`.`TipoExemplar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exemplar_EstatutoExemplar1`
    FOREIGN KEY (`EstatutoExemplar_id`)
    REFERENCES `yii2saramago`.`EstatutoExemplar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exemplar_Obra1`
    FOREIGN KEY (`Obra_id`)
    REFERENCES `yii2saramago`.`Obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exemplar_Biblioteca1`
    FOREIGN KEY (`Biblioteca_id`)
    REFERENCES `yii2saramago`.`Biblioteca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Analitico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Analitico` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `paginas` VARCHAR(45) NULL,
  `Monografia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Analitico_Monografia1_idx` (`Monografia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Analitico_Monografia1`
    FOREIGN KEY (`Monografia_id`)
    REFERENCES `yii2saramago`.`Monografia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Autor` (
  `id` INT NOT NULL,
  `primeiroNome` VARCHAR(45) NULL,
  `segundoNome` VARCHAR(45) NULL,
  `apelido` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `bibliografia` VARCHAR(45) NULL,
  `dataNascimento` VARCHAR(45) NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `orcid` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Reprografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Reprografia` (
  `id` INT NOT NULL,
  `dataPedido` DATE NULL,
  `dataConcluido` DATE NULL,
  `paginas` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `notaOpac` VARCHAR(45) NULL,
  `operador` VARCHAR(45) NULL,
  `Obra_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Reprografia_Obra1_idx` (`Obra_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reprografia_Obra1`
    FOREIGN KEY (`Obra_id`)
    REFERENCES `yii2saramago`.`Obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Curso` (
  `id` INT NOT NULL,
  `codCurso` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`UC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`UC` (
  `id` INT NOT NULL,
  `designacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Leitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Leitor` (
  `id` INT NOT NULL,
  `codBarras` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  `idDoc` VARCHAR(45) NULL,
  `dataNascimento` VARCHAR(45) NULL,
  `morada` VARCHAR(45) NULL,
  `localidade` VARCHAR(45) NULL,
  `codPostal` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `operador` VARCHAR(45) NULL,
  `telemovel` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `mail2` VARCHAR(45) NULL,
  `localidade` VARCHAR(45) NULL,
  `dataRegisto` DATE NULL,
  `dataAtualizacao` DATE NULL,
  `Biblioteca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Leitor_Biblioteca1_idx` (`Biblioteca_id` ASC) VISIBLE,
  CONSTRAINT `fk_Leitor_Biblioteca1`
    FOREIGN KEY (`Biblioteca_id`)
    REFERENCES `yii2saramago`.`Biblioteca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Funcionario` (
  `id` INT NOT NULL,
  `departamento` VARCHAR(45) NULL,
  `Leitor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Funcionario_Leitor1_idx` (`Leitor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Leitor1`
    FOREIGN KEY (`Leitor_id`)
    REFERENCES `yii2saramago`.`Leitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`LeituraRecomendada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`LeituraRecomendada` (
  `id` INT NOT NULL,
  `dataInicial` DATE NULL,
  `dataFinal` DATE NULL,
  `Obra_id` INT NOT NULL,
  `Funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LeituraRecomendada_Obra1_idx` (`Obra_id` ASC) VISIBLE,
  INDEX `fk_LeituraRecomendada_Funcionario1_idx` (`Funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_LeituraRecomendada_Obra1`
    FOREIGN KEY (`Obra_id`)
    REFERENCES `yii2saramago`.`Obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LeituraRecomendada_Funcionario1`
    FOREIGN KEY (`Funcionario_id`)
    REFERENCES `yii2saramago`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Aluno` (
  `id` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  `Leitor_id` INT NOT NULL,
  `Curso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Aluno_Leitor1_idx` (`Leitor_id` ASC) VISIBLE,
  INDEX `fk_Aluno_Curso1_idx` (`Curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Leitor1`
    FOREIGN KEY (`Leitor_id`)
    REFERENCES `yii2saramago`.`Leitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `yii2saramago`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Requisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Requisicao` (
  `id` INT NOT NULL,
  `dataEmprestimo` DATE NULL,
  `levantamento` VARCHAR(45) NULL,
  `entregaPrevista` DATE NULL,
  `dataDevolucao` DATE NULL,
  `renovacoes` VARCHAR(45) NULL,
  `Leitor_id` INT NOT NULL,
  `Exemplar_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Requisicao_Leitor1_idx` (`Leitor_id` ASC) VISIBLE,
  INDEX `fk_Requisicao_Exemplar1_idx` (`Exemplar_id` ASC) VISIBLE,
  CONSTRAINT `fk_Requisicao_Leitor1`
    FOREIGN KEY (`Leitor_id`)
    REFERENCES `yii2saramago`.`Leitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requisicao_Exemplar1`
    FOREIGN KEY (`Exemplar_id`)
    REFERENCES `yii2saramago`.`Exemplar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Reserva` (
  `id` INT NOT NULL,
  `dataReserva` DATE NULL,
  `estadoReserva` VARCHAR(45) NULL,
  `dataFecho` DATE NULL,
  `notaReserva` VARCHAR(45) NULL,
  `Leitor_id` INT NOT NULL,
  `Exemplar_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Reserva_Leitor1_idx` (`Leitor_id` ASC) VISIBLE,
  INDEX `fk_Reserva_Exemplar1_idx` (`Exemplar_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Leitor1`
    FOREIGN KEY (`Leitor_id`)
    REFERENCES `yii2saramago`.`Leitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Exemplar1`
    FOREIGN KEY (`Exemplar_id`)
    REFERENCES `yii2saramago`.`Exemplar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`ReservasPosto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`ReservasPosto` (
  `id` INT NOT NULL,
  `dataPedido` DATE NULL,
  `dataReserva` DATE NULL,
  `notaInterna` VARCHAR(45) NULL,
  `notaReservaOpac` VARCHAR(45) NULL,
  `estadoReserva` VARCHAR(45) NULL,
  `Leitor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ReservasPosto_Leitor1_idx` (`Leitor_id` ASC) VISIBLE,
  CONSTRAINT `fk_ReservasPosto_Leitor1`
    FOREIGN KEY (`Leitor_id`)
    REFERENCES `yii2saramago`.`Leitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`TipoLeitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`TipoLeitor` (
  `id` INT NOT NULL,
  `estatuto` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `quantidadeExemplares` INT NULL,
  `prazoDias` VARCHAR(45) NULL,
  `registoOpac` VARCHAR(45) NULL,
  `notas` VARCHAR(45) NULL,
  `Leitor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TipoLeitor_Leitor1_idx` (`Leitor_id` ASC) VISIBLE,
  CONSTRAINT `fk_TipoLeitor_Leitor1`
    FOREIGN KEY (`Leitor_id`)
    REFERENCES `yii2saramago`.`Leitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`TipoPTrabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`TipoPTrabalho` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `designacao` VARCHAR(45) NULL,
  `totalLugares` VARCHAR(45) NULL,
  `notaOpac` VARCHAR(45) NULL,
  `notaInterna` VARCHAR(45) NULL,
  `ativoOpac` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`PostoTrabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`PostoTrabalho` (
  `id` INT NOT NULL,
  `designacao` VARCHAR(45) NULL,
  `lugar` VARCHAR(45) NULL,
  `notaOpac` VARCHAR(45) NULL,
  `notaInterna` VARCHAR(45) NULL,
  `ReservasPosto_id` INT NOT NULL,
  `TipoPTrabalho_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PostoTrabalho_ReservasPosto1_idx` (`ReservasPosto_id` ASC) VISIBLE,
  INDEX `fk_PostoTrabalho_TipoPTrabalho1_idx` (`TipoPTrabalho_id` ASC) VISIBLE,
  CONSTRAINT `fk_PostoTrabalho_ReservasPosto1`
    FOREIGN KEY (`ReservasPosto_id`)
    REFERENCES `yii2saramago`.`ReservasPosto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PostoTrabalho_TipoPTrabalho1`
    FOREIGN KEY (`TipoPTrabalho_id`)
    REFERENCES `yii2saramago`.`TipoPTrabalho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`TipoIrregularidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`TipoIrregularidade` (
  `id` INT NOT NULL,
  `irregularidade` VARCHAR(45) NULL,
  `dias` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Irregularidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Irregularidade` (
  `id` INT NOT NULL,
  `dataInicial` DATE NULL,
  `TipoIrregularidade_id` INT NOT NULL,
  `Leitor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Irregularidade_TipoIrregularidade1_idx` (`TipoIrregularidade_id` ASC) VISIBLE,
  INDEX `fk_Irregularidade_Leitor1_idx` (`Leitor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Irregularidade_TipoIrregularidade1`
    FOREIGN KEY (`TipoIrregularidade_id`)
    REFERENCES `yii2saramago`.`TipoIrregularidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Irregularidade_Leitor1`
    FOREIGN KEY (`Leitor_id`)
    REFERENCES `yii2saramago`.`Leitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`ConsultaTReal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`ConsultaTReal` (
  `id` INT NOT NULL,
  `dataHora` DATE NULL,
  `dataHoraFinal` VARCHAR(45) NULL,
  `operador` VARCHAR(45) NULL,
  `Leitor_id` INT NOT NULL,
  `Exemplar_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ConsultaTReal_Leitor1_idx` (`Leitor_id` ASC) VISIBLE,
  INDEX `fk_ConsultaTReal_Exemplar1_idx` (`Exemplar_id` ASC) VISIBLE,
  CONSTRAINT `fk_ConsultaTReal_Leitor1`
    FOREIGN KEY (`Leitor_id`)
    REFERENCES `yii2saramago`.`Leitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConsultaTReal_Exemplar1`
    FOREIGN KEY (`Exemplar_id`)
    REFERENCES `yii2saramago`.`Exemplar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Config` (
  `id` INT NOT NULL,
  `key` VARCHAR(45) NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Noticias` (
  `id` INT NOT NULL,
  `interface` VARCHAR(45) NULL,
  `dataPublicacao` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Reprografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Reprografia` (
  `id` INT NOT NULL,
  `dataPedido` DATE NULL,
  `dataConcluido` DATE NULL,
  `paginas` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `notaOpac` VARCHAR(45) NULL,
  `operador` VARCHAR(45) NULL,
  `Obra_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Reprografia_Obra1_idx` (`Obra_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reprografia_Obra1`
    FOREIGN KEY (`Obra_id`)
    REFERENCES `yii2saramago`.`Obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Autor_has_Analitico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Autor_has_Analitico` (
  `Autor_id` INT NOT NULL,
  `Analitico_id` INT NOT NULL,
  PRIMARY KEY (`Autor_id`, `Analitico_id`),
  INDEX `fk_Autor_has_Analitico_Analitico1_idx` (`Analitico_id` ASC) VISIBLE,
  INDEX `fk_Autor_has_Analitico_Autor1_idx` (`Autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_has_Analitico_Autor1`
    FOREIGN KEY (`Autor_id`)
    REFERENCES `yii2saramago`.`Autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Analitico_Analitico1`
    FOREIGN KEY (`Analitico_id`)
    REFERENCES `yii2saramago`.`Analitico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Autor_has_Obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Autor_has_Obra` (
  `Autor_id` INT NOT NULL,
  `Obra_id` INT NOT NULL,
  PRIMARY KEY (`Autor_id`, `Obra_id`),
  INDEX `fk_Autor_has_Obra_Obra1_idx` (`Obra_id` ASC) VISIBLE,
  INDEX `fk_Autor_has_Obra_Autor1_idx` (`Autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_has_Obra_Autor1`
    FOREIGN KEY (`Autor_id`)
    REFERENCES `yii2saramago`.`Autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Obra_Obra1`
    FOREIGN KEY (`Obra_id`)
    REFERENCES `yii2saramago`.`Obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`SugAquisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`SugAquisicao` (
  `id` INT NOT NULL,
  `googleBooksID` VARCHAR(45) NULL,
  `Obra_id` INT NOT NULL,
  `Leitor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SugAquisicao_Obra1_idx` (`Obra_id` ASC) VISIBLE,
  INDEX `fk_SugAquisicao_Leitor1_idx` (`Leitor_id` ASC) VISIBLE,
  CONSTRAINT `fk_SugAquisicao_Obra1`
    FOREIGN KEY (`Obra_id`)
    REFERENCES `yii2saramago`.`Obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SugAquisicao_Leitor1`
    FOREIGN KEY (`Leitor_id`)
    REFERENCES `yii2saramago`.`Leitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`UC_has_LeituraRecomendada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`UC_has_LeituraRecomendada` (
  `UC_id` INT NOT NULL,
  `LeituraRecomendada_id` INT NOT NULL,
  PRIMARY KEY (`UC_id`, `LeituraRecomendada_id`),
  INDEX `fk_UC_has_LeituraRecomendada_LeituraRecomendada1_idx` (`LeituraRecomendada_id` ASC) VISIBLE,
  INDEX `fk_UC_has_LeituraRecomendada_UC1_idx` (`UC_id` ASC) VISIBLE,
  CONSTRAINT `fk_UC_has_LeituraRecomendada_UC1`
    FOREIGN KEY (`UC_id`)
    REFERENCES `yii2saramago`.`UC` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UC_has_LeituraRecomendada_LeituraRecomendada1`
    FOREIGN KEY (`LeituraRecomendada_id`)
    REFERENCES `yii2saramago`.`LeituraRecomendada` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Curso_has_UC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Curso_has_UC` (
  `Curso_id` INT NOT NULL,
  `UC_id` INT NOT NULL,
  PRIMARY KEY (`Curso_id`, `UC_id`),
  INDEX `fk_Curso_has_UC_UC1_idx` (`UC_id` ASC) VISIBLE,
  INDEX `fk_Curso_has_UC_Curso1_idx` (`Curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_has_UC_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `yii2saramago`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_UC_UC1`
    FOREIGN KEY (`UC_id`)
    REFERENCES `yii2saramago`.`UC` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2saramago`.`Leitor_has_Reprografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2saramago`.`Leitor_has_Reprografia` (
  `Leitor_id` INT NOT NULL,
  `Reprografia_id` INT NOT NULL,
  PRIMARY KEY (`Leitor_id`, `Reprografia_id`),
  INDEX `fk_Leitor_has_Reprografia_Reprografia1_idx` (`Reprografia_id` ASC) VISIBLE,
  INDEX `fk_Leitor_has_Reprografia_Leitor1_idx` (`Leitor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Leitor_has_Reprografia_Leitor1`
    FOREIGN KEY (`Leitor_id`)
    REFERENCES `yii2saramago`.`Leitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Leitor_has_Reprografia_Reprografia1`
    FOREIGN KEY (`Reprografia_id`)
    REFERENCES `yii2saramago`.`Reprografia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
